spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.enterprise.calendar: DEBUG
    com.microsoft.graph: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
